## @package parameters
#  Parameters used in the aruco_slam.

covariance:
    Q_k: 0.01           ## Error coefficient of encoder
    R_x: 0.0005         ## Error coefficient of observation x
    R_y: 0.001          ## Error coefficient of observation y
    R_theta: 0.001      ## Error coefficient of observation theta

odom:
    kl: 0.05    ## Left wheel radius
    kr: 0.05    ## Left wheel radius
    b: 0.09     ## half of robot wheelbase

aruco:
    markers_dictionary: 16 ## cv::aruco::PREDEFINED_DICTIONARY_NAME
    marker_length: 0.27    ## Length of the aruco markers, without the white edge, the unit is a meter

frame:
    world_frame: "world"                                ##Galobal frame name
    camera_frame_optical: "camera_frame_optical"        ##Image frame name
    robot_frame_base: "base_link"                       ##Robot base link frame name

topic:
    image: /camera/image_raw    ## Subscribed topic for image msg including image sensor_msgs::ImageConstPtr and camera info sensor_msgs::CameraInfoConstPtr
    encoder: /encoder           ## Subscribed topic for encoder msg including vector with two wheels' anguler valocity std_msgs::Float32MultiArray::ConstPtr

map:
    map_file: "/home/liangyichen/catkin_ws/src/aruco_slam/map/map.txt" #Direction of map file with accurate information of real map







